export { ReactComponent as MenuIcon } from "./menu.svg"
export { ReactComponent as MoreIcon } from "./more.svg"
export { ReactComponent as NextIcon } from "./next.svg"
export { ReactComponent as PauseIcon } from "./pause.svg"
export { ReactComponent as PlayIcon } from "./play.svg"
export { ReactComponent as PrevIcon } from "./prev.svg"
export { ReactComponent as SearchIcon } from "./search.svg"
export { ReactComponent as SoundIcon } from "./sound.svg"
